### ISSUE TITLE
toggle button not working 

### ISSUE THREAD

**Issue by mrantry** [dcchacon/Web-Design-Challenge#1]
https://github.com/dcchacon/Web-Design-Challenge/blob/da6b1bfc8d0cf18d99f6eb3ed4b762788cd3cb89/index.html#L25

check this line out, particularly the `data-target` and `aria-controls` properties of the tag. Those need to match the *id of what you're wanting to collapse and expand*. In your case, this is `navbarToggleExternalContent`, not `navbarTogglerDemo03`. That should solve your problem.

**Comment by dcchacon** [comment]
Thank you for the explanation, I changed it to "navbarToggleExternalContent" but it didn't work. After reading your explanation, I was able to find the id "navbarNavDropdown" instead of "navbarToggleExternalContent" :)
